spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://my.dragon.com:3306/batch_test
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
      temp:
        # Spring Boot2需设置
        use_jdbc_metadata_defaults: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  batch:
    initialize-schema: always
