spring:
  redis:
    host: my.dragon.com
    port: 6379
    timeout: 5000
    database: 0
    # lettuce相关配置
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0