server:
  port: 8081

spring:
  application:
    name: provider-service    # 指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问。

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8080/eureka/   # 指定服务注册中心的位置。

